name: PHP WordPress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Tải xuống dependencies
      - name: Download Classic Editor plugin
        run: |
          wget -O classic-editor.zip https://downloads.wordpress.org/plugin/classic-editor.latest-stable.zip
          unzip classic-editor.zip

      # Cài đặt dependencies
      - name: Install Classic Editor plugin
        run: |
          wp plugin install classic-editor --activate

      # ... (Các bước khác cho project WordPress của bạn)
